// Generated with `lib/make.js`
'use strict';
const path = require('path');
const url = require('url');

const Umask = () => {};
const getLocalAddresses = () => [];
const semver = () => {};

exports.types = {
		'_auth' : [null, String],
	'access' : [null, 'restricted', 'public'],
	'all' : Boolean,
	'allow-same-version' : Boolean,
	'also' : [null, 'dev', 'development'],
	'audit' : Boolean,
	'audit-level' : [null, 'info', 'low', 'moderate', 'high', 'critical', 'none'],
	'auth-type' : ['legacy', 'web'],
	'before' : [null, Date],
	'bin-links' : Boolean,
	'browser' : [null, Boolean, String],
	'ca' : [null, String, Array],
	'cache' : path,
	'cache-max' : Number,
	'cache-min' : Number,
	'cafile' : path,
	'call' : String,
	'cert' : [null, String],
	'cidr' : [null, String, Array],
	'color' : ['always', Boolean],
	'commit-hooks' : Boolean,
	'cpu' : [null, String],
	'os' : [null, String],
	'depth' : [null, Number],
	'description' : Boolean,
	'dev' : Boolean,
	'diff' : [String, Array],
	'diff-ignore-all-space' : Boolean,
	'diff-name-only' : Boolean,
	'diff-no-prefix' : Boolean,
	'diff-dst-prefix' : String,
	'diff-src-prefix' : String,
	'diff-text' : Boolean,
	'diff-unified' : Number,
	'dry-run' : Boolean,
	'editor' : String,
	'engine-strict' : Boolean,
	'fetch-retries' : Number,
	'fetch-retry-factor' : Number,
	'fetch-retry-maxtimeout' : Number,
	'fetch-retry-mintimeout' : Number,
	'fetch-timeout' : Number,
	'force' : Boolean,
	'foreground-scripts' : Boolean,
	'format-package-lock' : Boolean,
	'fund' : Boolean,
	'git' : String,
	'git-tag-version' : Boolean,
	'global' : Boolean,
	'globalconfig' : path,
	'global-style' : Boolean,
	'heading' : String,
	'https-proxy' : [null, url],
	'if-present' : Boolean,
	'ignore-scripts' : Boolean,
	'include' : [Array, 'prod', 'dev', 'optional', 'peer'],
	'include-staged' : Boolean,
	'include-workspace-root' : Boolean,
	'init-author-email' : String,
	'init-author-name' : String,
	'init-author-url' : ['', url],
	'init-license' : String,
	'init-module' : path,
	'init-version' : semver,
	'init.author.email' : String,
	'init.author.name' : String,
	'init.author.url' : ['', url],
	'init.license' : String,
	'init.module' : path,
	'init.version' : semver,
	'install-links' : Boolean,
	'install-strategy' : ['hoisted', 'nested', 'shallow', 'linked'],
	'json' : Boolean,
	'key' : [null, String],
	'legacy-bundling' : Boolean,
	'legacy-peer-deps' : Boolean,
	'link' : Boolean,
	'local-address' : getLocalAddresses(),
	'sbom-format' : ['cyclonedx', 'spdx'],
	'sbom-type' : ['library', 'application', 'framework'],
	'location' : ['global', 'user', 'project'],
	'lockfile-version' : [null, 1, 2, 3, '1', '2', '3'],
	'loglevel' : ['silent', 'error', 'warn', 'notice', 'http', 'info', 'verbose', 'silly'],
	'logs-dir' : [null, path],
	'logs-max' : Number,
	'long' : Boolean,
	'maxsockets' : Number,
	'message' : String,
	'node-options' : [null, String],
	'noproxy' : [String, Array],
	'offline' : Boolean,
	'omit' : [Array, 'dev', 'optional', 'peer'],
	'omit-lockfile-registry-resolved' : Boolean,
	'only' : [null, 'prod', 'production'],
	'optional' : [null, Boolean],
	'otp' : [null, String],
	'package' : [String, Array],
	'package-lock' : Boolean,
	'package-lock-only' : Boolean,
	'pack-destination' : String,
	'parseable' : Boolean,
	'prefer-dedupe' : Boolean,
	'prefer-offline' : Boolean,
	'prefer-online' : Boolean,
	'prefix' : path,
	'preid' : String,
	'production' : [null, Boolean],
	'progress' : Boolean,
	'provenance' : Boolean,
	'provenance-file' : path,
	'proxy' : [null, false, url],
	'read-only' : Boolean,
	'rebuild-bundle' : Boolean,
	'registry' : url,
	'replace-registry-host' : ['npmjs', 'never', 'always', String],
	'save' : Boolean,
	'save-bundle' : Boolean,
	'save-dev' : Boolean,
	'save-exact' : Boolean,
	'save-optional' : Boolean,
	'save-peer' : Boolean,
	'save-prefix' : String,
	'save-prod' : Boolean,
	'scope' : String,
	'script-shell' : [null, String],
	'searchexclude' : String,
	'searchlimit' : Number,
	'searchopts' : String,
	'searchstaleness' : Number,
	'shell' : String,
	'shrinkwrap' : Boolean,
	'sign-git-commit' : Boolean,
	'sign-git-tag' : Boolean,
	'strict-peer-deps' : Boolean,
	'strict-ssl' : Boolean,
	'tag' : String,
	'tag-version-prefix' : String,
	'timing' : Boolean,
	'umask' : Umask,
	'unicode' : Boolean,
	'update-notifier' : Boolean,
	'usage' : Boolean,
	'user-agent' : String,
	'userconfig' : path,
	'version' : Boolean,
	'versions' : Boolean,
	'viewer' : String,
	'which' : [null, Number],
	'workspace' : [String, Array],
	'workspaces' : [null, Boolean],
	'workspaces-update' : Boolean,
	'yes' : [null, Boolean],
	}
	