/// <reference types="node" />
export const types: {
    _auth: (StringConstructor | null)[];
    access: (string | null)[];
    all: BooleanConstructor;
    'allow-same-version': BooleanConstructor;
    also: (string | null)[];
    audit: BooleanConstructor;
    'audit-level': (string | null)[];
    'auth-type': string[];
    before: (DateConstructor | null)[];
    'bin-links': BooleanConstructor;
    browser: (StringConstructor | BooleanConstructor | null)[];
    ca: (StringConstructor | ArrayConstructor | null)[];
    cache: path.PlatformPath;
    'cache-max': NumberConstructor;
    'cache-min': NumberConstructor;
    cafile: path.PlatformPath;
    call: StringConstructor;
    cert: (StringConstructor | null)[];
    cidr: (StringConstructor | ArrayConstructor | null)[];
    color: (string | BooleanConstructor)[];
    'commit-hooks': BooleanConstructor;
    cpu: (StringConstructor | null)[];
    os: (StringConstructor | null)[];
    depth: (NumberConstructor | null)[];
    description: BooleanConstructor;
    dev: BooleanConstructor;
    diff: (StringConstructor | ArrayConstructor)[];
    'diff-ignore-all-space': BooleanConstructor;
    'diff-name-only': BooleanConstructor;
    'diff-no-prefix': BooleanConstructor;
    'diff-dst-prefix': StringConstructor;
    'diff-src-prefix': StringConstructor;
    'diff-text': BooleanConstructor;
    'diff-unified': NumberConstructor;
    'dry-run': BooleanConstructor;
    editor: StringConstructor;
    'engine-strict': BooleanConstructor;
    'fetch-retries': NumberConstructor;
    'fetch-retry-factor': NumberConstructor;
    'fetch-retry-maxtimeout': NumberConstructor;
    'fetch-retry-mintimeout': NumberConstructor;
    'fetch-timeout': NumberConstructor;
    force: BooleanConstructor;
    'foreground-scripts': BooleanConstructor;
    'format-package-lock': BooleanConstructor;
    fund: BooleanConstructor;
    git: StringConstructor;
    'git-tag-version': BooleanConstructor;
    global: BooleanConstructor;
    globalconfig: path.PlatformPath;
    'global-style': BooleanConstructor;
    heading: StringConstructor;
    'https-proxy': (typeof url | null)[];
    'if-present': BooleanConstructor;
    'ignore-scripts': BooleanConstructor;
    include: (string | ArrayConstructor)[];
    'include-staged': BooleanConstructor;
    'include-workspace-root': BooleanConstructor;
    'init-author-email': StringConstructor;
    'init-author-name': StringConstructor;
    'init-author-url': (string | typeof url)[];
    'init-license': StringConstructor;
    'init-module': path.PlatformPath;
    'init-version': () => void;
    'init.author.email': StringConstructor;
    'init.author.name': StringConstructor;
    'init.author.url': (string | typeof url)[];
    'init.license': StringConstructor;
    'init.module': path.PlatformPath;
    'init.version': () => void;
    'install-links': BooleanConstructor;
    'install-strategy': string[];
    json: BooleanConstructor;
    key: (StringConstructor | null)[];
    'legacy-bundling': BooleanConstructor;
    'legacy-peer-deps': BooleanConstructor;
    link: BooleanConstructor;
    'local-address': never[];
    'sbom-format': string[];
    'sbom-type': string[];
    location: string[];
    'lockfile-version': (string | number | null)[];
    loglevel: string[];
    'logs-dir': (path.PlatformPath | null)[];
    'logs-max': NumberConstructor;
    long: BooleanConstructor;
    maxsockets: NumberConstructor;
    message: StringConstructor;
    'node-options': (StringConstructor | null)[];
    noproxy: (StringConstructor | ArrayConstructor)[];
    offline: BooleanConstructor;
    omit: (string | ArrayConstructor)[];
    'omit-lockfile-registry-resolved': BooleanConstructor;
    only: (string | null)[];
    optional: (BooleanConstructor | null)[];
    otp: (StringConstructor | null)[];
    package: (StringConstructor | ArrayConstructor)[];
    'package-lock': BooleanConstructor;
    'package-lock-only': BooleanConstructor;
    'pack-destination': StringConstructor;
    parseable: BooleanConstructor;
    'prefer-dedupe': BooleanConstructor;
    'prefer-offline': BooleanConstructor;
    'prefer-online': BooleanConstructor;
    prefix: path.PlatformPath;
    preid: StringConstructor;
    production: (BooleanConstructor | null)[];
    progress: BooleanConstructor;
    provenance: BooleanConstructor;
    'provenance-file': path.PlatformPath;
    proxy: (boolean | typeof url | null)[];
    'read-only': BooleanConstructor;
    'rebuild-bundle': BooleanConstructor;
    registry: typeof url;
    'replace-registry-host': (string | StringConstructor)[];
    save: BooleanConstructor;
    'save-bundle': BooleanConstructor;
    'save-dev': BooleanConstructor;
    'save-exact': BooleanConstructor;
    'save-optional': BooleanConstructor;
    'save-peer': BooleanConstructor;
    'save-prefix': StringConstructor;
    'save-prod': BooleanConstructor;
    scope: StringConstructor;
    'script-shell': (StringConstructor | null)[];
    searchexclude: StringConstructor;
    searchlimit: NumberConstructor;
    searchopts: StringConstructor;
    searchstaleness: NumberConstructor;
    shell: StringConstructor;
    shrinkwrap: BooleanConstructor;
    'sign-git-commit': BooleanConstructor;
    'sign-git-tag': BooleanConstructor;
    'strict-peer-deps': BooleanConstructor;
    'strict-ssl': BooleanConstructor;
    tag: StringConstructor;
    'tag-version-prefix': StringConstructor;
    timing: BooleanConstructor;
    umask: () => void;
    unicode: BooleanConstructor;
    'update-notifier': BooleanConstructor;
    usage: BooleanConstructor;
    'user-agent': StringConstructor;
    userconfig: path.PlatformPath;
    version: BooleanConstructor;
    versions: BooleanConstructor;
    viewer: StringConstructor;
    which: (NumberConstructor | null)[];
    workspace: (StringConstructor | ArrayConstructor)[];
    workspaces: (BooleanConstructor | null)[];
    'workspaces-update': BooleanConstructor;
    yes: (BooleanConstructor | null)[];
};
import path = require("path");
import url = require("url");
